IDYGS81-BryanBautista/Controllers/RolesController.cs
using IDYGS81_BryanBautista.Context;
using IDYGS81_BryanBautista.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System;
using System.Linq;

namespace IDYGS81_BryanBautista.Controllers
{
    public class RolesController : Controller
    {

        private readonly ApplicationDbContext _context;
        public RolesController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var res = _context.Roles.ToList();
            return View(res);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Rol request)
        {
            try
            {
                Rol roles = new Rol();
                roles.Nombre = request.Nombre;
                roles.Descripcion = request.Descripcion;
                _context.Roles.Add(roles);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var rol = _context.Roles.Find(id);
                return View(rol);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Editar(int id, Rol request)
        {
            try
            {
                Rol roles = new Rol();
                roles = _context.Roles.Find(id);
                roles.Nombre = request.Nombre;
                roles.Descripcion = request.Descripcion;
                _context.Roles.Update(roles);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            try
            {
                var rol = _context.Roles.Find(id);
                return View(rol);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Eliminar(int id, Rol request)
        {
            try
            {
                Rol roles = new Rol();
                roles = _context.Roles.Find(id);
                _context.Roles.Remove(roles);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }


    }
}

IDYGS81-BryanBautista/Controllers/ServicioController.cs
using IDYGS81_BryanBautista.Context;
using IDYGS81_BryanBautista.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace IDYGS81_BryanBautista.Controllers
{
    public class ServicioController : Controller
    {
        private readonly ApplicationDbContext _context;
        public ServicioController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var res = _context.Servicios.ToList();
            return View(res);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Servicio request)
        {
            try
            {
                Servicio servicio = new Servicio();
                servicio.Titulo= request.Titulo;  
                servicio.Descripcion = request.Descripcion;
                _context.Servicios.Add(servicio);
                await _context.SaveChangesAsync();  
                return RedirectToAction(nameof(Index));


            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }
        
        }

        [HttpGet]
        public IActionResult Editar(int id) {
            try
            {
                var servicio = _context.Servicios.Find(id);
                return View(servicio);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }
        
        }
        [HttpPost]
        public async Task<IActionResult> Editar(int id, Servicio request)
        {
            try
            {
                Servicio service = new Servicio();
                service = _context.Servicios.Find(id);
                service.Titulo = request.Titulo;
                service.Descripcion = request.Descripcion;
                _context.Servicios.Update(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            try
            {
                var servicio = _context.Servicios.Find(id);
                return View(servicio);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Eliminar(int id, Servicio request)
        {
            try
            {
                Servicio service = new Servicio();
                service = _context.Servicios.Find(id); 
                _context.Servicios.Remove(service);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }

    }
}

IDYGS81-BryanBautista/Controllers/UsuarioController.cs
using IDYGS81_BryanBautista.Context;
using IDYGS81_BryanBautista.Models;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using System;
using System.Linq;
using Microsoft.AspNetCore.Identity;

namespace IDYGS81_BryanBautista.Controllers
{
    public class UsuarioController : Controller
    {

        private readonly ApplicationDbContext _context;
        public UsuarioController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var res = _context.Usuarios.ToList();
            return View(res);
        }
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Crear(Usuario request)
        {
            try
            {
                Usuario usuario = new Usuario();
                usuario.Nombre = request.Nombre;
                usuario.Apellido = request.Apellido;
                usuario.Correo = request.Correo;
                usuario.Password = request.Password;
                usuario.FKRol = request.FKRol;
                _context.Usuarios.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }

        [HttpGet]
        public IActionResult Editar(int id)
        {
            try
            {
                var usuario = _context.Usuarios.Find(id);
                return View(usuario);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Editar (int id, Usuario request)
        {
            try
            {
                Usuario usuario = new Usuario();
                usuario = _context.Usuarios.Find(id);
                usuario.Nombre = request.Nombre;
                usuario.Apellido = request.Apellido;
                usuario.Correo = request.Correo;
                usuario.Password = request.Password;
                usuario.FKRol = request.FKRol;
                _context.Usuarios.Update(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            try
            {
                var usuario = _context.Usuarios.Find(id);
                return View(usuario);

            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
        [HttpPost]
        public async Task<IActionResult> Eliminar(int id, Usuario request)
        {
            try
            {
                Usuario usuario = new Usuario();
                usuario = _context.Usuarios.Find(id);
                _context.Usuarios.Remove(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {

                throw new Exception("Surgio un error " + ex.Message);
            }

        }
    }
}

IDYGS81-BryanBautista/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IDYGS81_BryanBautista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IDYGS81_BryanBautista</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Hola">Hola</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IDYGS81_BryanBautista - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

IDYGS81-BryanBautista/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] -Dashboard </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/dashboard.css" />
    <script src="https://kit.fontawesome.com/8d6a339a43.js" crossorigin="anonymous"></script>
</head>
<body>

    <div class="wrapper">
        <!---sidebar-->
        <div class="sidebar">
            <div class="sidebar_logo">
                <img src="img/favicon.png" alt="codingscape">
                <a href="#">WEB</a>
            </div>
            <ul class="sidebar_items">
                <li class="sidebar_items_list">
                    <a asp-controller="Servicio" asp-action="Index" class="sidebar_nav_item">
                        <i class='bx bx-home-alt-2'></i>
                        <p>Servicios </p>
                    </a>
                </li>
                <li class="sidebar_items_list">
                    <a asp-controller="Usuario" asp-action="Index" class="sidebar_nav_item">
                        <i class='bx bxs-dashboard'></i>
                        <p>Usuarios</p>
                    </a>
                </li>
                <li class="sidebar_items_list">
                    <a asp-controller="Roles" asp-action="Index" class="sidebar_nav_item">
                        <i class='bx bxs-calendar'></i>
                        <p>Roles</p>
                    </a>
                </li>

                <li class="sidebar_items_list">
                    <a href="#" class="sidebar_nav_item">
                        <i class='bx bx-log-out'></i>
                        <p>Logout</p>
                    </a>
                </li>
            </ul>
            <div class="sidebar-toggle">
                <i class='bx bxs-chevron-left'></i>
                <p></p>
            </div>
        </div>
    </div>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>